"""add class and xp

Revision ID: 638c45c4c901
Revises: dff21e78b770
Create Date: 2018-09-14 19:40:27.352595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638c45c4c901'
down_revision = 'dff21e78b770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('classname', sa.String(length=10), nullable=True))
    op.add_column('character', sa.Column('level', sa.SmallInteger(), nullable=False, server_default="1"))
    op.add_column('character', sa.Column('xp', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade():
    # You will have to change automatic drop column commands to use batch_alter_table
    with op.batch_alter_table('character') as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('xp')
        batch_op.drop_column('classname')
