"""add races

Revision ID: ac6070c5086d
Revises: f2a38803aa5b
Create Date: 2018-09-17 23:38:46.301655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6070c5086d'
down_revision = 'f2a38803aa5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('cha_mod', sa.SmallInteger(), nullable=False, server_default="0"))
    op.add_column('character', sa.Column('com_mod', sa.SmallInteger(), nullable=False, server_default="0"))
    op.add_column('character', sa.Column('con_mod', sa.SmallInteger(), nullable=False, server_default="0"))
    op.add_column('character', sa.Column('dex_mod', sa.SmallInteger(), nullable=False, server_default="0"))
    op.add_column('character', sa.Column('gender', sa.Boolean(), nullable=False, server_default="1"))
    op.add_column('character', sa.Column('int_mod', sa.SmallInteger(), nullable=False, server_default="0"))
    op.add_column('character', sa.Column('race', sa.String(length=10), nullable=True))
    op.add_column('character', sa.Column('str_mod', sa.SmallInteger(), nullable=False, server_default="0"))
    op.add_column('character', sa.Column('wis_mod', sa.SmallInteger(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('character') as batch_op:
        batch_op.drop_column('wis_mod')
        batch_op.drop_column('str_mod')
        batch_op.drop_column('race')
        batch_op.drop_column('int_mod')
        batch_op.drop_column('gender')
        batch_op.drop_column('dex_mod')
        batch_op.drop_column('con_mod')
        batch_op.drop_column('com_mod')
        batch_op.drop_column('cha_mod')
