"""Remove Level

Revision ID: f2a38803aa5b
Revises: 638c45c4c901
Create Date: 2018-09-17 14:12:45.794008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a38803aa5b'
down_revision = '638c45c4c901'
branch_labels = None
depends_on = None


def upgrade():
    # You will have to change automatic drop column commands to use batch_alter_table
    with op.batch_alter_table('character') as batch_op:
        batch_op.drop_column('level')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('level', sa.SMALLINT(), server_default=sa.text("'1'"), nullable=False))
    # ### end Alembic commands ###
